
# docker compose for development environment

name: alexwbt-com-dev

services:
  alexwbt:
    container_name: alexwbt-dev
    image: dev/alexwbt
    build:
      context: alexwbt
      dockerfile: ../_docker/dev/alexwbt.Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    command: ["npm", "start"]
    restart: unless-stopped
