# docker compose for development environment

name: alexwbt-com-dev

services:

  alexwbt:
    container_name: alexwbt-dev
    image: alexwbt-dev
    build:
      context: ./alexwbt
      dockerfile: ../_docker/dev/alexwbt-dev.Dockerfile
    environment:
      WATCHPACK_POLLING: true
      WDS_SOCKET_PORT: ${ALEXWBT_DEV_PORT:-3000}
    volumes:
      - "vscode-server:/root/.vscode-server"
      - "./alexwbt/src:/app/src"
      - "./alexwbt/public:/app/public"
      - "./alexwbt/tsconfig.json:/app/tsconfig.json"
      - "./_dev/alexwbt-config.js:/app/public/config.js"
    ports:
      - ${ALEXWBT_DEV_PORT:-3000}:3000
    restart: unless-stopped
    stdin_open: true
    tty: true

  alexwbt-api:
    container_name: alexwbt-api-dev
    image: alexwbt-api-dev
    build:
      context: ./alexwbt-api
      dockerfile: ../_docker/dev/alexwbt-api-dev.Dockerfile
    volumes:
      - "vscode-server:/root/.vscode-server"
      - "./alexwbt-api/src:/app/src"
      - "./alexwbt-api/prisma:/app/prisma"
      - "./alexwbt-api/nodemon.json:/app/nodemon.json"
      - "./alexwbt-api/tsconfig.json:/app/tsconfig.json"
      - "./_dev/alexwbt-api.env:/app/.env"
    ports:
      - ${ALEXWBT_API_DEV_PORT:-3001}:3000
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  vscode-server:
    external: false
