# docker compose for development environment

name: alexwbt-com-dev

services:
  alexwbt:
    container_name: alexwbt-dev
    image: alexwbt-dev
    build:
      context: ./alexwbt
      dockerfile: ../_docker/dev/alexwbt-dev.Dockerfile
    environment:
      WATCHPACK_POLLING: true
      WDS_SOCKET_PORT: 13000
    volumes:
      - "vscode-server:/root/.vscode-server"
      - "./alexwbt/src:/app/src"
      - "./alexwbt/public:/app/public"
      - "./alexwbt/tsconfig.json:/app/tsconfig.json"
    ports:
      - 13000:3000
    command: [ "npm", "start" ]
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  vscode-server:
    external: false
