version: "3"

services:
  controller:
    image: alexwbt/alexwbt.com-controller
    container_name: controller
    restart: always
    environment:
      PORT: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/compose:/opt/compose/compose
      - ${PWD}/e:/opt/compose/e

networks:
  default:
    external:
      name: net1
