version: "3"

services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    restart: always

    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_FRONTEND_URL: https://keycloak.alexwbt.com/auth/
      DB_VENDOR: postgres
      DB_ADDR: ${KEYCLOAK_DB_ADDR}
      DB_PORT: ${KEYCLOAK_DB_PORT}
      DB_SCHEMA: keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD_FILE: /env/secret/db_password_file

      JDBC_PARAMS: enabledTLSProtocols=TLSv1.2

      # using JDBC_PING for HA mode
      # JGROUPS_DISCOVERY_EXTERNAL_IP: ${IP}
      # JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      # KEYCLOAK_TCP_PORT: ${KEYCLOAK_TCP_PORT}
    ports:
      - ${KEYCLOAK_TCP_PORT}:${KEYCLOAK_TCP_PORT}

    volumes:
      - ${PWD}/env/secret/keycloak-db_password_file:/env/secret/db_password_file
      - ${PWD}/volumes/keycloak/discovery:/opt/jboss/tools/cli/jgroups/discovery

    entrypoint: /opt/jboss/tools/docker-entrypoint.sh

networks:
  default:
    external:
      name: net1
